apiVersion: apps/v1
kind: Deployment
metadata:
  name: deo-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deo-backend
  template:
    metadata:
      labels:
        app: deo-backend
    spec:
      containers:
      - name: deo-backend
        image: ghcr.io/simon-raaber/deo-webapp-backend:latest
        args: ["--urls", "http://*.3000"]
        ports:
        - containerPort: 3000
